import Vue from 'vue';
import App from './App.vue';

new Vue({
  el: '#app',
  render: h => h(App)
});

const obvious_bug = 3;
obvious_bug = 45; // This will throw an error

const const_token = 'eyJraWQiOiJLTkFvV2JUc0IzbHdFSExOUkZHaUIxM0RYNHg5elMwSlMwVzIzT0FiVzBrIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULnhVT29mbVplRFJPbFJnT2tlcGkwTWtSb20wYzR0WmYwa2dSb1ZqLWFWZzQub2FyMzF0ZzlkaGpZdEV2UVMwaDciLCJpc3MiOiJodHRwczovL2Rldi02MTIyMzMub2t0YXByZXZpZXcuY29tL29hdXRoMi9kZWZhdWx0IiwiYXVkIjoiYXBpOi8vZGVmYXVsdCIsInN1YiI6InNocmF2YW5rQHNlbnNlaGF3ay5jb20iLCJpYXQiOjE3MzI4NzQ2NzgsImV4cCI6MTczMjk2MTA3OCwiY2lkIjoiMG9hb2pvYmdxZmhZc1BoUG8waDciLCJ1aWQiOiIwMHVoOHE5bmUyczhSRWJnMTBoNyIsInNjcCI6WyJvcGVuaWQiXSwiYXV0aF90aW1lIjoxNzMyNTUzMjA5LCJmaXJzdG5hbWUiOiJTaHJhdmFuIiwicm9sZSI6ImhhY2tlciIsInVzZXJfaWQiOiI1YjlQY2pxdnZjIiwiZW1haWwiOiJzaHJhdmFua0BzZW5zZWhhd2suY29tIiwic3RhdHVzIjoiQUNUSVZFIiwibGFzdG5hbWUiOiJLYXVzaGlrIn0.X4OUh2egectCyXxxpkses0DDZAO_6sjmQJ7m_Ubpv9fCjI2pOayLXGrJ1S-JanCOvjoYM-taYv9DXr4akHTpB_UK8OO5G5jpcO_wVVQ2WngKFfPb9FwrDdEyYvucOWQoXQuJ3yu92RxU8mZ_pCeWDXYdYWOFUyT9i7opZP9C3sQoRKC2OXVwImRxQOtK1sv0_7RJaNt3DkmYjTtSm5bQyeyWktLatvzxBLaaexIK4HIPCB1kMMjNmhfOoARBIdAbrWGGC0CT3U6Yv7Ujosuapf18ZzkXWd6KEDb6bK8oeUOySeK125qaFcLq-pi1YfmvD50CePaWVqRTXuaK9TMNog';
localStorage.setItem('const_token', const_token);

console.log('new stuff');
